### ISSUE TITLE
[REQ] license setting on GH

### ISSUE THREAD

**Issue by forart** [adammurdocknh/YAMS#13]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [Effects section](https://github.com/forart/HyMPS/blob/main/AudioFXs.md)), can you please set licensing terms on this git ?

Our "problem" is that does not generates the correct badge: 

![](https://flat.badgen.net/github/license/adammurdocknh/YAMS?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/adammurdocknh/YAMS/?label=LICENSE)

...maybe it's a GH setup issue ?

Thanks in advance.

**Comment by adammurdocknh** [comment]
That's because I didn't forgot a license haha. It was for a student design competition for the audio engineering society and I kind of forgot about it. I updated the license.

**Comment by MarcoRavich** [comment]
Thanks
